export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESSED = 'REGISTER_SUCCESSED'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const UPDATE_STATUS_ERROR = 'UPDATE_STATUS_ERROR'
export const SHOW_MODAL = 'SHOW_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SHOW_CREATE_ACC_MODAL = 'SHOW_CREATE_ACC_MODAL'
export const SHOW_LOGIN_ACC_MODAL = 'SHOW_LOGIN_ACC_MODAL'
export const CREATE_COUNTRY_REQUESTED = 'CREATE_COUNTRY_REQUESTED'
export const CREATE_COUNTRY_SUCCESSED = 'CREATE_COUNTRY_SUCCESSED'
export const CREATE_COUNTRY_FAILED = 'CREATE_COUNTRY_FAILED'
export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST'
export const FETCH_COUNTRY_SUCCED = 'FETCH_COUNTRY_SUCCED'
export const FETCH_COUNTRY_FAILED = 'FETCH_COUNTRY_FAILED'
export const DELETE_COUNTRY_REQUESTED = 'DELETE_COUNTRY_REQUESTED'
export const DELETE_COUNTRY_SUCCESSED = 'DELETE_COUNTRY_SUCCESSED'
export const DELETE_COUNTRY_FAILED = 'DELETE_COUNTRY_FAILED'

export const GET_INFO_COUNTRY_ITEM_SUCCED = 'GET_INFO_COUNTRY_ITEM_SUCCED'
export const GET_INFO_COUNTRY_ITEM_FAILED = 'GET_INFO_COUNTRY_ITEM_FAILED'
export const GET_DATA_ROW_TABLE_REQUESTED = 'GET_DATA_ROW_TABLE_REQUESTED'
export const GET_DATA_ROW_TABLE_SUCCED = 'GET_DATA_ROW_TABLE_SUCCED'
export const GET_DATA_ROW_TABLE_FAILED = 'GET_DATA_ROW_TABLE_FAILED'
export const SEND_DATA_ROW_INTO_STORE = 'SEND_DATA_ROW_INTO_STORE'
export const CHANGE_STATUS_EDIT = 'CHANGE_STATUS_EDIT'

export const UPDATE_DATA_COUNTRY_REQUESTED = 'UPDATE_DATA_COUNTRY_REQUESTED'
export const UPDATE_DATA_COUNTRY_SUCCED = 'UPDATE_DATA_COUNTRY_SUCCED'
export const UPDATE_DATA_COUNTRY_FAILED = 'UPDATE_DATA_COUNTRY_FAILED'
















