


export const LOGIN_REQUESTED = 'LOGIN_REQUESTED'
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'




export const UPDATE_LOGIN_REQUEST = 'UPDATE_LOGIN_REQUEST'
export const UPDATE_LOGIN_SUCCESS = 'UPDATE_LOGIN_SUCCESS'
export const UPDATE_LOGIN_FAILED = 'UPDATE_LOGIN_FAILED'




export const LOGOUT = 'LOGOUT'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESSED = 'REGISTER_SUCCESSED'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const UPDATE_STATUS_ERROR = 'UPDATE_STATUS_ERROR'
export const SHOW_MODAL = 'SHOW_MODAL'
export const SHOW_MODAL_LOGIN = 'SHOW_MODAL_LOGIN'
export const SHOW_MODAL_REGISTER = 'SHOW_MODAL_REGISTER'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const CLOSE_MODAL_LOGIN = 'CLOSE_MODAL_LOGIN'
export const CLOSE_MODAL_REGISTER = 'CLOSE_MODAL_REGISTER'
export const SHOW_CREATE_ACC_MODAL = 'SHOW_CREATE_ACC_MODAL'
export const SHOW_LOGIN_ACC_MODAL = 'SHOW_LOGIN_ACC_MODAL'


export const CREATE_COUNTRY_REQUESTED = 'CREATE_COUNTRY_REQUESTED'
export const CREATE_COUNTRY_SUCCESSED = 'CREATE_COUNTRY_SUCCESSED'
export const CREATE_COUNTRY_FAILED = 'CREATE_COUNTRY_FAILED'



export const CREATE_PLACE_REQUESTED = 'CREATE_PLACE_REQUESTED'
export const CREATE_PLACE_SUCCESSED = 'CREATE_PLACE_SUCCESSED'
export const CREATE_PLACE_FAILED = 'CREATE_PLACE_FAILED'




export const CREATE_TOUR_REQUESTED = 'CREATE_TOUR_REQUESTED'
export const CREATE_TOUR_SUCCESSED = 'CREATE_TOUR_SUCCESSED'
export const CREATE_TOUR_FAILED = 'CREATE_TOUR_FAILED'



export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST'
export const FETCH_COUNTRY_SUCCED = 'FETCH_COUNTRY_SUCCED'
export const FETCH_COUNTRY_FAILED = 'FETCH_COUNTRY_FAILED'



export const FETCH_PLACE_REQUEST = 'FETCH_PLACE_REQUEST'
export const FETCH_PLACE_SUCCED = 'FETCH_PLACE_SUCCED'
export const FETCH_PLACE_FAILED = 'FETCH_PLACE_FAILED'






export const FETCH_TOUR_REQUEST = 'FETCH_TOUR_REQUEST'
export const FETCH_TOUR_SUCCED = 'FETCH_TOUR_SUCCED'
export const FETCH_TOUR_FAILED = 'FETCH_TOUR_FAILED'






export const FETCH_INFO_TOUR_REQUEST = 'FETCH_INFO_TOUR_REQUEST'
export const FETCH_INFO_TOUR_SUCCED = 'FETCH_INFO_TOUR_SUCCED'
export const FETCH_INFO_TOUR_FAILED = 'FETCH_INFO_TOUR_FAILED'








export const FETCH_REVIEWS_LIST_REQUEST = 'FETCH_REVIEWS_LIST_REQUEST'
export const FETCH_REVIEWS_LIST_SUCCED = 'FETCH_REVIEWS_LIST_SUCCED'
export const FETCH_REVIEWS_LIST_FAILED = 'FETCH_REVIEWS_LIST_FAILED'












export const SUBMIT_USER_REVIEW_REQUEST = 'SUBMIT_USER_REVIEW_REQUEST'
export const SUBMIT_USER_REVIEW_SUCCED = 'SUBMIT_USER_REVIEW_SUCCED'
export const SUBMIT_USER_REVIEW_FAILED = 'SUBMIT_USER_REVIEW_FAILED'





export const RESET_STATE_IN_STORE = 'RESET_STATE_IN_STORE'
export const RESET_STATUS_BOOKING_TOUR = 'RESET_STATUS_BOOKING_TOUR'
export const RESET_LOGIN_STATUS = 'RESET_LOGIN_STATUS'










export const BOOKING_TOUR_REQUEST = 'BOOKING_TOUR_REQUEST'
export const BOOKING_TOUR_SUCCED = 'BOOKING_TOUR_SUCCED'
export const BOOKING_TOUR_FAILED = 'BOOKING_TOUR_FAILED'




export const DELETE_COUNTRY_REQUESTED = 'DELETE_COUNTRY_REQUESTED'
export const DELETE_COUNTRY_SUCCESSED = 'DELETE_COUNTRY_SUCCESSED'
export const DELETE_COUNTRY_FAILED = 'DELETE_COUNTRY_FAILED'





export const DELETE_PLACE_REQUESTED = 'DELETE_PLACE_REQUESTED'
export const DELETE_PLACE_SUCCESSED = 'DELETE_PLACE_SUCCESSED'
export const DELETE_PLACE_FAILED = 'DELETE_PLACE_FAILED'







export const DELETE_TOUR_REQUESTED = 'DELETE_TOUR_REQUESTED'
export const DELETE_TOUR_SUCCESSED = 'DELETE_TOUR_SUCCESSED'
export const DELETE_TOUR_FAILED = 'DELETE_TOUR_FAILED'



export const GET_INFO_COUNTRY_ITEM_SUCCED = 'GET_INFO_COUNTRY_ITEM_SUCCED'
export const GET_INFO_COUNTRY_ITEM_FAILED = 'GET_INFO_COUNTRY_ITEM_FAILED'
export const GET_DATA_ROW_TABLE_REQUESTED = 'GET_DATA_ROW_TABLE_REQUESTED'
export const GET_DATA_ROW_TABLE_SUCCED = 'GET_DATA_ROW_TABLE_SUCCED'
export const GET_DATA_ROW_TABLE_FAILED = 'GET_DATA_ROW_TABLE_FAILED'
export const SEND_DATA_ROW_INTO_STORE = 'SEND_DATA_ROW_INTO_STORE'
export const CHANGE_STATUS_EDIT = 'CHANGE_STATUS_EDIT'


export const UPDATE_DATA_COUNTRY_REQUESTED = 'UPDATE_DATA_COUNTRY_REQUESTED'
export const UPDATE_DATA_COUNTRY_SUCCED = 'UPDATE_DATA_COUNTRY_SUCCED'
export const UPDATE_DATA_COUNTRY_FAILED = 'UPDATE_DATA_COUNTRY_FAILED'



export const UPDATE_DATA_PLACE_REQUESTED = 'UPDATE_DATA_PLACE_REQUESTED'
export const UPDATE_DATA_PLACE_SUCCED = 'UPDATE_DATA_PLACE_SUCCED'
export const UPDATE_DATA_PLACE_FAILED = 'UPDATE_DATA_PLACE_FAILED'




export const UPDATE_DATA_TOUR_REQUESTED = 'UPDATE_DATA_TOUR_REQUESTED'
export const UPDATE_DATA_TOUR_SUCCED = 'UPDATE_DATA_TOUR_SUCCED'
export const UPDATE_DATA_TOUR_FAILED = 'UPDATE_DATA_TOUR_FAILED'


export const DATA_ITEM_TOUR_REQUESTED = 'DATA_ITEM_TOUR_REQUESTED'


export const FETCH_DATA_PLACE_IN_COUNTRY_REQUESTED = 'FETCH_DATA_PLACE_IN_COUNTRY_REQUESTED'
export const FETCH_DATA_PLACE_IN_COUNTRY_SUCCED = 'FETCH_DATA_PLACE_IN_COUNTRY_SUCCED'
export const FETCH_DATA_PLACE_IN_COUNTRY_FAILED = 'FETCH_DATA_PLACE_IN_COUNTRY_FAILED'




export const FETCH_REVIEWS_REQUEST = 'FETCH_REVIEWS_REQUEST'
export const FETCH_REVIEWS_SUCCED = 'FETCH_REVIEWS_SUCCED'
export const FETCH_REVIEWS_FAILED = 'FETCH_REVIEWS_FAILED'



export const FETCH_TOP_LIST_DESTINATION_REQUESTED = 'FETCH_TOP_LIST_DESTINATION_REQUESTED'
export const FETCH_TOP_LIST_DESTINATION_SUCCED = 'FETCH_TOP_LIST_DESTINATION_SUCCED'
export const FETCH_TOP_LIST_DESTINATION_FAILED = 'FETCH_TOP_LIST_DESTINATION_FAILED'
















